### ISSUE TITLE
update playdoh for Django 1.6

### ISSUE THREAD

**Issue by andymckay** [mozilla/playdoh#169]
``` python
Traceback (most recent call last):
  File "manage.py", line 24, in <module>
    manage.setup_environ(__file__, more_pythonic=True)
  File "/Users/andy/.virtualenvs/solitude/lib/python2.7/site-packages/funfactory/manage.py", line 74, in setup_environ
    from django.core.management import execute_manager
ImportError: cannot import name execute_manager
```

`execute_manager` was removed after being deprecated in 1.4. `execute_from_command_line` now exists but I don't think that's a direct replacement

**Comment by auvipy** [comment]
update to 1.8! its LTS
